x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "auth-db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "db"
  POSTGRES_PASSWORD: "sybau1234"
  POSTGRES_USER: "postgres"

x-backend-app-environment: &x-backend-app-environment # APPLICATION
  APP_NAME: "goon"
  APP_VERSION: "0.0.1"
  # HTTP
  HTTP_PORT: "8080"
  HTTP_USE_PREFORK_MODE: "false"
  # Logger
  LOG_LEVEL: "debug"
  # Postgres
  PG_POOL_MAX: "2"
  PG_URL: "postgres://postgres:sybau1234@auth-db:5432/db"
  # Metrics
  METRICS_ENABLED: "true"
  # Swagger
  SWAGGER_ENABLED: "true"
  # Auth
  JWT_SECRET: "mysecretsybau"

services:
  auth-service:
    container_name: auth-service
    platform: linux/amd64
    build:
      context: ./services/auth
    environment:
      <<: *x-backend-app-environment
    ports:
      - "8080:8080"
    depends_on:
      - auth-db
    networks:
      app_network:
        aliases:
          - auth.lvh.me

  auth-db:
    image: postgres:16.2-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
    networks:
      app_network:
        aliases:
          - auth-db.lvh.me

networks:
  app_network:
    external: false

volumes:
  auth_db_data:
